package com.ecommerce.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    DUPLICATE_RESOURCE,
    OUT_OF_STOCK,
    INVALID_VOUCHER,
    VOUCHER_EXPIRED,
    VOUCHER_USAGE_LIMIT_REACHED,
    INVALID_ORDER_STATUS,
    INVALID_PAYMENT,
    BUSINESS_ERROR,
    INTERNAL_ERROR
}
